output: json
file: ""
distro: ""
add-cpes-if-none: false
output-template-file: ""
quiet: false
check-for-app-update: false
only-fixed: false
only-notfixed: false
platform: ""
search:
  scope: "Squashed"
  unindexed-archives: false
  indexed-archives: false
ignore: []
exclude: []
db:
  cache-dir: ./resources/vuln/.grype/db
  update-url: https://toolbox-data.anchore.io/grype/databases/listing.json
  ca-cert: ""
  auto-update: true
  validate-by-hash-on-start: false
  validate-age: false
  max-allowed-built-age: 0s
external-sources:
  enable: false
  maven:
    search-upstream: false
    base-url: ""
dev:
  profile-cpu: false
  profile-mem: false
fail-on-severity: ""
registry:
  insecure-skip-tls-verify: false
  insecure-use-http: false
  auth: []
log:
  structured: false
  level: trace
  file: ""
attestation:
  public-key: ""
  skip-verification: false
