output: 
  - "json"
quiet: false
file: ""
check-for-app-update: true
exclude: []
platform: ""
catalogers:
package:
  search-indexed-archives: true
  search-unindexed-archives: false
  cataloger:
    enabled: true
    scope: "squashed"
file-classification:
  cataloger:
    enabled: true
    scope: "squashed"
file-contents:
  cataloger:
    enabled: true
    scope: "squashed"
  skip-files-above-size: 1048576
  globs: []
file-metadata:
  cataloger:
    enabled: true
    scope: "squashed"
  digests: ["sha256"]
secrets:
  cataloger:
    enabled: true
    scope: "all-layers"
  reveal-values: false
  skip-files-above-size: 1048576
  additional-patterns: {}
  exclude-pattern-names: []
registry:
  insecure-skip-tls-verify: false
  insecure-use-http: false
  auth: [] 
attest:
  key: "cosign.key"
  password: ""
log:
  structured: false
  level: "error"
  file: ""
